# Generated by Django 5.1.4 on 2025-05-05 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_alter_novel_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='categories',
        ),
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novels', to='novels.category'),
        ),
    ]
