# Generated by Django 5.1.4 on 2025-05-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='author_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
