# Generated by Django 5.1.4 on 2025-05-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_chapter_author_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='author_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
