# Generated by Django 5.1.4 on 2025-05-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_chapter_author_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='author_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tác giả'),
        ),
    ]
