# Generated by Django 5.1.4 on 2025-05-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_novel_author_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='author_text',
        ),
        migrations.AddField(
            model_name='novel',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
    ]
